In [ ]:
import numpy as np

In [6]:
lst = [1,2,3,5]
np.array(lst)

array([1, 2, 3, 5])

In [2]:
import numpy as np

print("My numpy version is: ", np.__version__)


My numpy version is:  2.1.0


In [3]:
import numpy as np
print(np.__version__)


2.1.0


In [4]:
import numpy as np

# Your list
lst = [1, 2, 3, 5]

# Convert the list to a NumPy array
array = np.array(lst)

print(array)


[1 2 3 5]


In [1]:
import numpy as np
lst = [1,2,3,4,5]
np.array(lst)

array([1, 2, 3, 4, 5])