In [1]:
import numpy as np

In [2]:
print("My numpy version is: ", np.__version__)

My numpy version is:  2.1.0


In [44]:
np.array([1,2,3,4])


array([1, 2, 3, 4])

In [6]:
type(arr1)

numpy.ndarray

In [ ]:
np.array([[1,2,3],[3,4,5]])

array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.identity(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
np.arange(6)
np.arange(2,10,2)


array([2, 4, 6, 8])

In [ ]:
np.linspace(10,20,10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [46]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(1)


array([[0.85181938, 0.11458666, 0.54719994]])

In [ ]:
np.random.rand(4,3)


array([[0.17962783, 0.63008237, 0.62892516],
       [0.96690793, 0.9464481 , 0.99359694],
       [0.89508364, 0.25857366, 0.1562429 ],
       [0.82632416, 0.76931559, 0.57499779]])

In [48]:
np.random.randint(1,3)


1

In [52]:
np.random.randint(1,100,15)

array([32, 98, 79, 17, 36,  8, 29, 40, 24, 15, 11, 72, 24, 70,  3],
      dtype=int32)

In [53]:
np.random.randn(5)

array([-0.15389155,  0.50719825, -0.90181468,  1.49175324, -1.31554343])

In [68]:
arr1 = np.arange(25) 
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [70]:
arr1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [76]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [73]:
arr1.max()

np.int64(24)

In [74]:
arr1.min()

np.int64(0)

In [79]:
arr1.argmin()

np.int64(0)